name: Rust
permissions: write-all
on:
  push:
    branches: [ "tmp" ]
env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rs-action
      uses: chayleaf/rs-actions@33db31bf3f400589df4689c8c821ff45d1c31127
      with:
        publish-release: true
